### ISSUE TITLE
心跳CountDownTimer疑似有bug：出现异常：Can't create handler inside thread that has not called Looper.prepare

### ISSUE THREAD

**Issue by Summer006** [vilyever/AndroidSocketClient#24]
`java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                           at android.os.Handler.<init>(Handler.java:200)
                                                           at android.os.Handler.<init>(Handler.java:114)
                                                           at android.os.CountDownTimer$1.<init>(CountDownTimer.java:114)
                                                           at android.os.CountDownTimer.<init>(CountDownTimer.java:114)
                                                           at com.vilyever.socketclient.SocketClient$5.<init>(SocketClient.java:449)
                                                           at com.vilyever.socketclient.SocketClient.getHearBeatCountDownTimer(SocketClient.java:449)
                                                           at com.vilyever.socketclient.SocketClient$DisconnectionThread.run(SocketClient.java:1048)`

注释心跳功能相关代码后，运行(暂时)正常

**Comment by Blithe0306** [comment]
我也碰到这个问题了。

**Comment by Blithe0306** [comment]
我的怎么也连接不上
FATAL EXCEPTION: Thread-15621
                                                               Process: com.skzh.access, PID: 1961
                                                               java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                                   at android.os.Handler.<init>(Handler.java:200)
                                                                   at android.os.Handler.<init>(Handler.java:114)
                                                                   at android.os.CountDownTimer$1.<init>(CountDownTimer.java:114)
                                                                   at android.os.CountDownTimer.<init>(CountDownTimer.java:114)
                                                                   at com.vilyever.socketclient.SocketClient$5.<init>(SocketClient.java:449)
                                                                   at com.vilyever.socketclient.SocketClient.getHearBeatCountDownTimer(SocketClient.java:449)
                                                                   at com.vilyever.socketclient.SocketClient$DisconnectionThread.run(SocketClient.java:1048)

**Comment by Summer006** [comment]
哟，你的异常粘贴出来居然格式完好？
出问题的地方是心跳CountDownTimer那里，你把源码复制过去，把心跳相关代码全部注释掉，就正常了

**Comment by Blithe0306** [comment]
楼主的例子 没有报错，他是在TestServer中处理了吧

**Comment by vilyever** [comment]
疏忽了，应该是第一次连接就失败人话会触发，断开时在线程中初始化CountDownTimer导致。
SocketClient.java中1048行没有判断CountDownTimer是否为null。
手边暂时没有工具修改，可以直接先用源码修改，我尽快弄好。

**Comment by Blithe0306** [comment]
好吧 坐等啊 什么时候能弄好

**Comment by vilyever** [comment]
用记事本改了下，应该是没问题，还是请帮忙试一下3.0.2可以了没有
