### ISSUE TITLE
TimerTick报错

### ISSUE THREAD

**Issue by githubzyh123** [vilyever/AndroidSocketClient#28]
Socket客户端与服务端连接，长时间运行后，客户端会报错， 下面代码第一行报错：  
if (getSocketConfigure().getSocketPacketHelper().isSendTimeoutEnabled()
                && getLastSendMessageTime() != NoSendingTime) {
            if (currentTime - getLastSendMessageTime() >= getSocketConfigure().getSocketPacketHelper().getSendTimeout()) {
                disconnect();
            }
        }
报错如下：
10-11 09:10:55.186 24080-5718/com.njsyg.myapplication E/AndroidRuntime: FATAL EXCEPTION: Thread-1887
                                                                        java.lang.NullPointerException
                                                                            at com.vilyever.socketclient.SocketClient.__i__onTimeTick(SocketClient.java:954)
                                                                            at com.vilyever.socketclient.SocketClient.access$600(SocketClient.java:33)
                                                                            at com.vilyever.socketclient.SocketClient$5$1.run(SocketClient.java:455)
                                                                            at java.lang.Thread.run(Thread.java:856)

**Comment by vilyever** [comment]
可以告知一下版本号吗
NullPointerException能否断点看到是哪一个变量为NULL
好像不太好重现

**Comment by qiuixn** [comment]
我也是这个错误,请问之前是怎么解决的
