### ISSUE TITLE
Android 8.0 运行时直接崩溃问题

### ISSUE THREAD

**Issue by luoh1234** [vilyever/AndroidSocketClient#63]
Process: com.test.demo, PID: 20589
                                                   java.lang.IllegalThreadStateException: Thread already started
                                                       at java.lang.Thread.checkNotStarted(Thread.java:849)
                                                       at java.lang.Thread.start(Thread.java:1059)
                                                       at com.vilyever.socketclient.SocketClient.__i__onConnected(SocketClient.java:707)
                                                       at com.vilyever.socketclient.SocketClient.access$1000(SocketClient.java:33)
                                                       at com.vilyever.socketclient.SocketClient$7.run(SocketClient.java:694)
                                                       at android.os.Handler.handleCallback(Handler.java:742)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5524)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by luoh1234** [comment]
线程运行时再启动会报错
