### ISSUE TITLE
一直报错说没有设置setReadStrategy

### ISSUE THREAD

**Issue by niebiao** [vilyever/AndroidSocketClient#67]
logcat日志一直显示我没有设置读取的规则，但是我已经设置为AutoReadToTrailer，希望有人可以帮我解答一下，谢谢

ava.lang.NullPointerException: Attempt to invoke virtual method 'com.vilyever.socketclient.helper.SocketPacketHelper$ReadStrategy com.vilyever.socketclient.helper.SocketPacketHelper.getReadStrategy()' on a null object reference
                                                     at com.vilyever.socketclient.SocketClient$ReceiveThread.run(SocketClient.java:1211)

**Comment by niebiao** [comment]
if (self.getSocketPacketHelper().getReadStrategy() == SocketPacketHelper.ReadStrategy.Manually) {
                return;
            }
直接获取getSocketPacketHelper就可以了，就不会出现问题

**Comment by WangIdea** [comment]
我也遇到了这个问题 ，而且是今天突然就报错了， 之前一直没有错误，是什么原因呢。
ava.lang.NullPointerException: Attempt to invoke virtual method 'com.vilyever.socketclient.helper.SocketPacketHelper$ReadStrategy com.vilyever.socketclient.helper.SocketPacketHelper.getReadStrategy()' on a null object reference
at com.vilyever.socketclient.SocketClient$ReceiveThread.run(SocketClient.java:1211)
