### ISSUE TITLE
java.lang.IllegalThreadStateException

### ISSUE THREAD

**Issue by WangIdea** [vilyever/AndroidSocketClient#74]
[2021-03-29 13:22:19:310][E][Thread-41:Crash]java.lang.IllegalThreadStateException
	at java.lang.Thread.start(Thread.java:724)
	at com.vilyever.socketclient.SocketClient.disconnect(SocketClient.java:72)
	at com.vilyever.socketclient.SocketClient$ReceiveThread.run(SocketClient.java:1337)
	
![image](https://user-images.githubusercontent.com/24712696/112804249-c6403680-90a6-11eb-8dc1-0ced1ff4ad11.png)
![image](https://user-images.githubusercontent.com/24712696/112804351-e8d24f80-90a6-11eb-8833-6ac667222f5e.png)

偶尔会出发这个异常  直接崩溃，我找了你的源码  没有找到问题，请教你一下！

**Comment by wqbs369** [comment]
有可能是出异常的时候，socket已经关闭了，所以你再调用disconnect就出异常了，你可以加一个try catch或者调用 前判断一下socket是否open,













--

dick.wei




在 2021-03-29 15:54:24，"WangIdea" ***@***.***> 写道：

[2021-03-29 13:22:19:310][E][Thread-41:Crash]java.lang.IllegalThreadStateException
at java.lang.Thread.start(Thread.java:724)
at com.vilyever.socketclient.SocketClient.disconnect(SocketClient.java:72)
at com.vilyever.socketclient.SocketClient$ReceiveThread.run(SocketClient.java:1337)




偶尔会出发这个异常 直接崩溃，我找了你的源码 没有找到问题，请教你一下！

**Comment by WangIdea** [comment]
我在线程start处加了try catch  异常能捕获到   偶尔出现
